### ISSUE TITLE
SimpleSupress effects will not work after loading a save in singleplayer

### ISSUE THREAD

**Issue by WheelAxle** [SzwedzikPL/SimpleSuppress#5]
Can be reproduced by just loading a save after dying in a singleplayer senario. Effects will not play from then on until the mission is reloaded entirely.

Video Link: https://www.youtube.com/watch?v=k_A05BP2I6I

**Comment by SzwedzikPL** [comment]
Thank you for report!

Issue has been fixed in version 1.1.0.
